WITH CTE_A (Number, STYLE_NAME,STYLE, COUNTS) AS (
    
  SELECT ROW_NUMBER() OVER (ORDER BY (select STYLE_NAME)) as Number, STYLE_NAME,STYLE, COUNTS  FROM
  (
      SELECT STYLE_NAME, 'BEER_STYLE' AS STYLE , (SELECT COUNT(*) FROM D_BEER_STYLE) AS COUNTS FROM D_BEER_STYLE
      UNION
      SELECT MICROSTYLE_NAME, 'BEER_MICRO' AS STYLE, (SELECT COUNT(*) FROM D_BEER_MICROSTYLE) AS COUNTS FROM D_BEER_MICROSTYLE
      UNION
      SELECT BROADCLASS_NAME, 'FLAVOR_BROAD' AS STYLE , (SELECT COUNT(*) FROM D_FLAVOR_BROADCLASS) FROM D_FLAVOR_BROADCLASS
      UNION
      SELECT STYLE_NAME, 'FLAVOR_STYLE' AS STYLE, (SELECT COUNT(*) FROM D_FLAVOR_STYLE) FROM D_FLAVOR_STYLE
      UNION
      SELECT BROADCLASS_NAME, 'SPIRITS_BROAD' AS STYLE,(SELECT COUNT(*) FROM D_SPIRITS_BROADCLASS)  FROM D_SPIRITS_BROADCLASS
      UNION
      SELECT TYPE_NAME, 'SPIRITS_TYPE' AS STYLE , (SELECT COUNT(*) FROM D_SPIRITS_TYPE) FROM D_SPIRITS_TYPE
      UNION
      SELECT STYLE_NAME, 'WINE_STYLE' AS STYLE , (SELECT COUNT(*) FROM D_WINE_STYLE) FROM D_WINE_STYLE
      UNION
      SELECT SUBSTYLE_NAME, 'WINE_SUBSTYLE' AS STYLE,(SELECT COUNT(*) FROM D_WINE_SUBSTYLE) FROM D_WINE_SUBSTYLE
      UNION
      SELECT VARIETAL_NAME, 'WINE_VARIETAL' AS STYLE,(SELECT COUNT(*) FROM D_WINE_VARIETAL)   FROM D_WINE_VARIETAL
   )A
) ,
 CTE_B (Number,STYLE_NAME,STYLE,COUNTS) AS 
(
 SELECT ROW_NUMBER() OVER (ORDER BY (select STYLE_NAME)) as Number, STYLE_NAME, STYLE,COUNTS  FROM(
  
   SELECT STYLE_NAME, 'BEER_STYLE' AS STYLE , (SELECT COUNT(*) FROM D_BEER_STYLE) AS COUNTS FROM D_BEER_STYLE
UNION
SELECT MICROSTYLE_NAME, 'BEER_MICRO' AS STYLE, (SELECT COUNT(*) FROM D_BEER_MICROSTYLE) AS COUNTS FROM D_BEER_MICROSTYLE
UNION
SELECT BROADCLASS_NAME, 'FLAVOR_BROAD' AS STYLE , (SELECT COUNT(*) FROM D_FLAVOR_BROADCLASS) FROM D_FLAVOR_BROADCLASS
UNION
SELECT STYLE_NAME, 'FLAVOR_STYLE' AS STYLE, (SELECT COUNT(*) FROM D_FLAVOR_STYLE) FROM D_FLAVOR_STYLE
UNION
SELECT BROADCLASS_NAME, 'SPIRITS_BROAD' AS STYLE,(SELECT COUNT(*) FROM D_SPIRITS_BROADCLASS)  FROM D_SPIRITS_BROADCLASS
UNION
SELECT TYPE_NAME, 'SPIRITS_TYPE' AS STYLE , (SELECT COUNT(*) FROM D_SPIRITS_TYPE) FROM D_SPIRITS_TYPE
UNION
SELECT STYLE_NAME, 'WINE_STYLE' AS STYLE , (SELECT COUNT(*) FROM D_WINE_STYLE) FROM D_WINE_STYLE
UNION
SELECT SUBSTYLE_NAME, 'WINE_SUBSTYLE' AS STYLE,(SELECT COUNT(*) FROM D_WINE_SUBSTYLE) FROM D_WINE_SUBSTYLE
UNION
SELECT VARIETAL_NAME, 'WINE_VARIETAL' AS STYLE,(SELECT COUNT(*) FROM D_WINE_VARIETAL)   FROM D_WINE_VARIETAL
) B
  )
  

SELECT   CONCAT( ANUMBER ,'-' , BNumber) AS Number,
CONCAT(ASTYLE_NAME ,' ' , BSTYLE_NAME) AS STYLE_NAME, 
CONCAT(ASTYLE, ' ', BSTYLE) AS STLYE ,
ACOUNTS as CT
FROM
(
SELECT  a.Number as ANUMBER ,b.Number AS BNUMBER, 
  a.STYLE_NAME AS  ASTYLE_NAME,a.STYLE AS ASTYLE
  , a.COUNTS AS ACOUNTS,  
  b.STYLE_NAME AS BSTYLE_NAME,
  b.STYLE AS BSTYLE, b.COUNTS AS BCOUNTS FROM CTE_A a, CTE_B b
)


